const task = [
  {
    id: 1,
    task: "Landing page product",
    logo: "",
    members: "7",
    completed: "80",
    folders: 42,
  },
  {
    id: 2,
    task: "Appartment app",
    logo: "",
    members: "7",
    completed: "50",
    folders: 24,
  },
  {
    id: 3,
    task: "Learning App",
    logo: "",
    members: "7",
    completed: "65",
    folders: 48,
  },
  {
    id: 4,
    task: "Expense App",
    logo: "",
    members: "7",
    completed: "90",
    folders: 72,
  },
  {
    id: 5,
    task: "Quiz App",
    logo: "",
    members: "7",
    completed: "60",
    folders: 64,
  },
  {
    id: 6,
    task: "Food Delivery App",
    logo: "",
    members: "7",
    completed: "30",
    folders: 18,
  },
];
export default task;
